// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jtecbwnegeqprrmxpdao.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp0ZWNid25lZ2VxcHJybXhwZGFvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg4NDUxOTcsImV4cCI6MjA3NDQyMTE5N30.5yr3kV9GGAqHz0WdITLohPfiM6OKmeWTq8G5x1wXHbg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});